name: Build report
on:
  push:
    branches: [main]
    paths:
      - "report/**"
  pull_request:
    branches: [main]
    paths:
      - "report/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: "0"
          lfs: true

      - uses: ./.github/actions/report

      # - name: Upload Artifacts
      #   uses: actions/upload-pages-artifact@v3
      #   with:
      #     path: "public/"

  # deploy:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   if: github.event_name == 'push'

  #   permissions:
  #     pages: write
  #     id-token: write

  #   environment:
  #     name: github-pages
  #     url: ${{ steps.deployment.outputs.page_url }}

  #   steps:
  #     - name: Deploy
  #       id: deployment
  #       uses: actions/deploy-pages@v4
