name: Build site

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: "0"
          lfs: true

      - uses: typst-community/setup-typst@v4
        with:
          typst-version: ${{ vars.TYPST_VERSION }}

      - name: Install pandoc
        uses: pandoc/actions/setup@v1
        with:
          version: 3.8.2.1

      - name: Install OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5.0.0
          dune-cache: true
          opam-disable-sandboxing: true

      - name: Cache external repositories
        uses: actions/cache@v4
        with:
          path: |
            report/Linden
            report/RegElk
          key: repos-${{ hashFiles('report/.vscode/settings.json') }}

      - name: Cache RegElk build artifacts
        uses: actions/cache@v4
        with:
          path: |
            report/RegElk/_build
            report/regex_frequencies-*.csv
          key: regelk-build-${{ hashFiles('report/.vscode/settings.json') }}

      - name: Build site
        run: |
          ./public/generate.sh

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v4
        if: github.event_name == 'push'
        with:
          path: "public/"

  deploy:
    needs: build
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
